#:schema node_modules/wrangler/config-schema.json
name = "assistente-marketing-digital"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "assistente_marketing_db"
database_id = "production-db-id" # Substituir com ID real do banco de produção depois

[[d1_databases]]
binding = "DB_LOCAL"
database_name = "assistente_marketing_db_local"
database_id = "local-dev-db"
preview_database_id = "local-dev-db"

